"""Remove restrictions to id and manager

Revision ID: 70670f161a07
Revises: 92ecaaaa5d33
Create Date: 2025-04-03 10:11:16.711937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70670f161a07'
down_revision: Union[str, None] = '92ecaaaa5d33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_teams_manager', table_name='teams')
    op.create_index(op.f('ix_teams_manager'), 'teams', ['manager'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_manager'), table_name='teams')
    op.create_index('ix_teams_manager', 'teams', ['manager'], unique=True)
    # ### end Alembic commands ###
