"""Adjust item to Leagues

Revision ID: 8a5b4152cc2a
Revises: d5e4f2014a53
Create Date: 2025-04-04 17:24:43.117887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a5b4152cc2a'
down_revision: Union[str, None] = 'd5e4f2014a53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('tipo_liga', sa.Enum('LIGA_TACTICA', 'LIGA_INTERNA', 'TORNEO', 'BATALLAS', name='tipoliga'), nullable=True))
    op.add_column('leagues', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.drop_index('ix_leagues_season', table_name='leagues')
    op.create_index(op.f('ix_leagues_tipo_liga'), 'leagues', ['tipo_liga'], unique=False)
    op.create_foreign_key(None, 'leagues', 'teams', ['creator_id'], ['id'])
    op.drop_column('leagues', 'season')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('season', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'leagues', type_='foreignkey')
    op.drop_index(op.f('ix_leagues_tipo_liga'), table_name='leagues')
    op.create_index('ix_leagues_season', 'leagues', ['season'], unique=False)
    op.drop_column('leagues', 'creator_id')
    op.drop_column('leagues', 'tipo_liga')
    # ### end Alembic commands ###
