"""Added manager column to teams

Revision ID: 96f73cc48cae
Revises: 548c0b6f8cec
Create Date: 2025-03-31 14:58:22.746916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96f73cc48cae'
down_revision: Union[str, None] = '548c0b6f8cec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_teams_clan'), 'teams', ['clan'], unique=False)
    op.create_index(op.f('ix_teams_manager'), 'teams', ['manager'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_manager'), table_name='teams')
    op.drop_index(op.f('ix_teams_clan'), table_name='teams')
    # ### end Alembic commands ###
