"""Added models and operations to Leagues

Revision ID: d5e4f2014a53
Revises: 70670f161a07
Create Date: 2025-04-04 15:55:23.539420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5e4f2014a53'
down_revision: Union[str, None] = '70670f161a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('league_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_matches_league_id'), 'matches', ['league_id'], unique=False)
    op.create_foreign_key(None, 'matches', 'leagues', ['league_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_index(op.f('ix_matches_league_id'), table_name='matches')
    op.drop_column('matches', 'league_id')
    # ### end Alembic commands ###
