/**
 * Mapeo completo de nombres de países y sus códigos ISO 2
 * Incluye países de todos los continentes y múltiples variantes en español e inglés
 */
export const COUNTRY_CODES = {
    // EUROPA
    'españa': 'es',
    'espana': 'es',
    'spain': 'es',
    'esp': 'es',
    'alemania': 'de',
    'germany': 'de',
    'ger': 'de',
    'deu': 'de',
    'francia': 'fr',
    'france': 'fr',
    'fra': 'fr',
    'italia': 'it',
    'italy': 'it',
    'ita': 'it',
    'reino unido': 'gb',
    'united kingdom': 'gb',
    'uk': 'gb',
    'gbr': 'gb',
    'inglaterra': 'gb',
    'england': 'gb',
    'eng': 'gb',
    'escocia': 'gb-sct',
    'scotland': 'gb-sct',
    'sco': 'gb-sct',
    'gales': 'gb-wls',
    'wales': 'gb-wls',
    'wal': 'gb-wls',
    'irlanda del norte': 'gb-nir',
    'northern ireland': 'gb-nir',
    'nir': 'gb-nir',
    'irlanda': 'ie',
    'ireland': 'ie',
    'irl': 'ie',
    'portugal': 'pt',
    'por': 'pt',
    'prt': 'pt',
    'holanda': 'nl',
    'países bajos': 'nl',
    'paises bajos': 'nl',
    'netherlands': 'nl',
    'ned': 'nl',
    'nld': 'nl',
    'bélgica': 'be',
    'belgica': 'be',
    'belgium': 'be',
    'bel': 'be',
    'suiza': 'ch',
    'switzerland': 'ch',
    'sui': 'ch',
    'che': 'ch',
    'austria': 'at',
    'aut': 'at',
    'dinamarca': 'dk',
    'denmark': 'dk',
    'den': 'dk',
    'dnk': 'dk',
    'noruega': 'no',
    'norway': 'no',
    'nor': 'no',
    'suecia': 'se',
    'sweden': 'se',
    'swe': 'se',
    'finlandia': 'fi',
    'finland': 'fi',
    'fin': 'fi',
    'islandia': 'is',
    'iceland': 'is',
    'isl': 'is',
    'grecia': 'gr',
    'greece': 'gr',
    'gre': 'gr',
    'grc': 'gr',
    'turquía': 'tr',
    'turquia': 'tr',
    'turkey': 'tr',
    'tur': 'tr',
    'polonia': 'pl',
    'poland': 'pl',
    'pol': 'pl',
    'rusia': 'ru',
    'russia': 'ru',
    'rus': 'ru',
    'ucrania': 'ua',
    'ukraine': 'ua',
    'ukr': 'ua',
    'república checa': 'cz',
    'republica checa': 'cz',
    'czech republic': 'cz',
    'czech': 'cz',
    'cze': 'cz',
    'hungría': 'hu',
    'hungria': 'hu',
    'hungary': 'hu',
    'hun': 'hu',
    'rumanía': 'ro',
    'rumania': 'ro',
    'romania': 'ro',
    'rom': 'ro',
    'rou': 'ro',
    'bulgaria': 'bg',
    'bul': 'bg',
    'bgr': 'bg',
    'croacia': 'hr',
    'croatia': 'hr',
    'cro': 'hr',
    'hrv': 'hr',
    'serbia': 'rs',
    'srb': 'rs',
    'eslovenia': 'si',
    'slovenia': 'si',
    'svn': 'si',
    'eslovaquia': 'sk',
    'slovakia': 'sk',
    'svk': 'sk',
    'albania': 'al',
    'alb': 'al',
    'macedonia': 'mk',
    'north macedonia': 'mk',
    'mkd': 'mk',
    'bosnia': 'ba',
    'bosnia y herzegovina': 'ba',
    'bosnia and herzegovina': 'ba',
    'bih': 'ba',
    'montenegro': 'me',
    'mne': 'me',
    'luxemburgo': 'lu',
    'luxembourg': 'lu',
    'lux': 'lu',
    'chipre': 'cy',
    'cyprus': 'cy',
    'cyp': 'cy',
    'malta': 'mt',
    'mlt': 'mt',
    'estonia': 'ee',
    'estonia': 'ee',
    'est': 'ee',
    'letonia': 'lv',
    'latvia': 'lv',
    'lva': 'lv',
    'lituania': 'lt',
    'lithuania': 'lt',
    'ltu': 'lt',
    'bielorrusia': 'by',
    'belarus': 'by',
    'blr': 'by',
    'moldova': 'md',
    'moldavia': 'md',
    'mda': 'md',
    'georgia': 'ge',
    'geo': 'ge',
    'armenia': 'am',
    'arm': 'am',
    'azerbaiyán': 'az',
    'azerbaiyan': 'az',
    'azerbaijan': 'az',
    'aze': 'az',
  
    // AMÉRICA
    'estados unidos': 'us',
    'eeuu': 'us',
    'united states': 'us',
    'usa': 'us',
    'méxico': 'mx',
    'mexico': 'mx',
    'mex': 'mx',
    'canadá': 'ca',
    'canada': 'ca',
    'can': 'ca',
    'brasil': 'br',
    'brazil': 'br',
    'bra': 'br',
    'argentina': 'ar',
    'arg': 'ar',
    'chile': 'cl',
    'chi': 'cl',
    'chl': 'cl',
    'colombia': 'co',
    'col': 'co',
    'perú': 'pe',
    'peru': 'pe',
    'per': 'pe',
    'uruguay': 'uy',
    'uru': 'uy',
    'paraguay': 'py',
    'par': 'py',
    'pry': 'py',
    'bolivia': 'bo',
    'bol': 'bo',
    'ecuador': 'ec',
    'ecu': 'ec',
    'venezuela': 've',
    'ven': 've',
    'costa rica': 'cr',
    'crc': 'cr',
    'panamá': 'pa',
    'panama': 'pa',
    'pan': 'pa',
    'guatemala': 'gt',
    'gua': 'gt',
    'gtm': 'gt',
    'honduras': 'hn',
    'hon': 'hn',
    'el salvador': 'sv',
    'slv': 'sv',
    'nicaragua': 'ni',
    'nic': 'ni',
    'cuba': 'cu',
    'cub': 'cu',
    'jamaica': 'jm',
    'jam': 'jm',
    'haití': 'ht',
    'haiti': 'ht',
    'hai': 'ht',
    'república dominicana': 'do',
    'republica dominicana': 'do',
    'dominican republic': 'do',
    'dom': 'do',
    'puerto rico': 'pr',
    'pur': 'pr',
    'belice': 'bz',
    'belize': 'bz',
    'blz': 'bz',
    'trinidad y tobago': 'tt',
    'trinidad and tobago': 'tt',
    'trinidad': 'tt',
    'barbados': 'bb',
    'brb': 'bb',
    'bahamas': 'bs',
    'bhs': 'bs',
    'guyana': 'gy',
    'guy': 'gy',
    'surinam': 'sr',
    'suriname': 'sr',
    'sur': 'sr',
  
    // ASIA
    'japón': 'jp',
    'japon': 'jp',
    'japan': 'jp',
    'jpn': 'jp',
    'china': 'cn',
    'chn': 'cn',
    'corea del sur': 'kr',
    'south korea': 'kr',
    'korea': 'kr',
    'kor': 'kr',
    'corea del norte': 'kp',
    'north korea': 'kp',
    'prk': 'kp',
    'india': 'in',
    'ind': 'in',
    'indonesia': 'id',
    'idn': 'id',
    'tailandia': 'th',
    'thailand': 'th',
    'tha': 'th',
    'vietnam': 'vn',
    'vnm': 'vn',
    'malasia': 'my',
    'malaysia': 'my',
    'mas': 'my',
    'mys': 'my',
    'singapur': 'sg',
    'singapore': 'sg',
    'sin': 'sg',
    'sgp': 'sg',
    'filipinas': 'ph',
    'philippines': 'ph',
    'phi': 'ph',
    'phl': 'ph',
    'arabia saudita': 'sa',
    'arabia saudi': 'sa',
    'arabia saudí': 'sa',
    'saudi arabia': 'sa',
    'ksa': 'sa',
    'sau': 'sa',
    'emiratos árabes unidos': 'ae',
    'emiratos arabes unidos': 'ae',
    'united arab emirates': 'ae',
    'uae': 'ae',
    'are': 'ae',
    'qatar': 'qa',
    'catar': 'qa',
    'qat': 'qa',
    'kuwait': 'kw',
    'kuw': 'kw',
    'bahréin': 'bh',
    'bahrein': 'bh',
    'bahrain': 'bh',
    'bhr': 'bh',
    'omán': 'om',
    'oman': 'om',
    'omn': 'om',
    'irán': 'ir',
    'iran': 'ir',
    'iri': 'ir',
    'irq': 'iq',
    'iraq': 'iq',
    'israel': 'il',
    'isr': 'il',
    'palestina': 'ps',
    'palestine': 'ps',
    'ple': 'ps',
    'jordania': 'jo',
    'jordan': 'jo',
    'jor': 'jo',
    'líbano': 'lb',
    'libano': 'lb',
    'lebanon': 'lb',
    'lbn': 'lb',
    'siria': 'sy',
    'syria': 'sy',
    'syr': 'sy',
    'uzbekistán': 'uz',
    'uzbekistan': 'uz',
    'uzb': 'uz',
    'kazajistán': 'kz',
    'kazajistan': 'kz',
    'kazakhstan': 'kz',
    'kaz': 'kz',
    'kirguistán': 'kg',
    'kirguistan': 'kg',
    'kyrgyzstan': 'kg',
    'kgz': 'kg',
    'tayikistán': 'tj',
    'tayikistan': 'tj',
    'tajikistan': 'tj',
    'tjk': 'tj',
    'turkmenistán': 'tm',
    'turkmenistan': 'tm',
    'tkm': 'tm',
    'pakistán': 'pk',
    'pakistan': 'pk',
    'pak': 'pk',
    'afganistán': 'af',
    'afganistan': 'af',
    'afghanistan': 'af',
    'afg': 'af',
    'bangladés': 'bd',
    'banglades': 'bd',
    'bangladesh': 'bd',
    'ban': 'bd',
    'bgd': 'bd',
    'sri lanka': 'lk',
    'sri': 'lk',
    'lka': 'lk',
    'nepal': 'np',
    'nep': 'np',
    'bután': 'bt',
    'butan': 'bt',
    'bhutan': 'bt',
    'bhu': 'bt',
    'maldivas': 'mv',
    'maldives': 'mv',
    'mdv': 'mv',
    'mongolia': 'mn',
    'mgl': 'mn',
    'mng': 'mn',
    'hong kong': 'hk',
    'hkg': 'hk',
    'taiwán': 'tw',
    'taiwan': 'tw',
    'tpe': 'tw',
    'macao': 'mo',
    'macau': 'mo',
    'mac': 'mo',
    'brunéi': 'bn',
    'brunei': 'bn',
    'bru': 'bn',
    'timor oriental': 'tl',
    'timor-leste': 'tl',
    'east timor': 'tl',
    'tls': 'tl',
    'camboya': 'kh',
    'cambodia': 'kh',
    'cam': 'kh',
    'khm': 'kh',
    'laos': 'la',
    'lao': 'la',
    'myanmar': 'mm',
    'birmania': 'mm',
    'burma': 'mm',
    'mya': 'mm',
  
    // ÁFRICA
    'egipto': 'eg',
    'egypt': 'eg',
    'egy': 'eg',
    'sudáfrica': 'za',
    'sudafrica': 'za',
    'south africa': 'za',
    'rsa': 'za',
    'zaf': 'za',
    'marruecos': 'ma',
    'morocco': 'ma',
    'mar': 'ma',
    'argelia': 'dz',
    'algeria': 'dz',
    'alg': 'dz',
    'túnez': 'tn',
    'tunez': 'tn',
    'tunisia': 'tn',
    'tun': 'tn',
    'nigeria': 'ng',
    'nga': 'ng',
    'ngr': 'ng',
    'ghana': 'gh',
    'camerún': 'cm',
    'camerun': 'cm',
    'cameroon': 'cm',
    'cmr': 'cm',
    'costa de marfil': 'ci',
    'côte d\'ivoire': 'ci',
    'ivory coast': 'ci',
    'civ': 'ci',
    'senegal': 'sn',
    'sen': 'sn',
    'kenia': 'ke',
    'kenya': 'ke',
    'ken': 'ke',
    'etiopía': 'et',
    'etiopia': 'et',
    'ethiopia': 'et',
    'eth': 'et',
    'angola': 'ao',
    'ang': 'ao',
    'tanzania': 'tz',
    'tan': 'tz',
    'tza': 'tz',
    'zimbabue': 'zw',
    'zimbabwe': 'zw',
    'zim': 'zw',
    'uganda': 'ug',
    'uga': 'ug',
    'ruanda': 'rw',
    'rwanda': 'rw',
    'rwa': 'rw',
    'zambia': 'zm',
    'zam': 'zm',
    'zmb': 'zm',
    'mozambique': 'mz',
    'moz': 'mz',
    'guinea': 'gn',
    'gui': 'gn',
    'gin': 'gn',
    'mali': 'ml',
    'mli': 'ml',
    'burkina faso': 'bf',
    'bfa': 'bf',
    'benín': 'bj',
    'benin': 'bj',
    'ben': 'bj',
    'gabón': 'ga',
    'gabon': 'ga',
    'gab': 'ga',
    'guinea ecuatorial': 'gq',
    'equatorial guinea': 'gq',
    'geq': 'gq',
    'república democrática del congo': 'cd',
    'republica democratica del congo': 'cd',
    'democratic republic of the congo': 'cd',
    'cod': 'cd',
    'república del congo': 'cg',
    'republica del congo': 'cg',
    'republic of the congo': 'cg',
    'cgo': 'cg',
    'liberia': 'lr',
    'lbr': 'lr',
    'sierra leona': 'sl',
    'sierra leone': 'sl',
    'sle': 'sl',
    'togo': 'tg',
    'tog': 'tg',
    'cabo verde': 'cv',
    'cape verde': 'cv',
    'cpv': 'cv',
    'gambia': 'gm',
    'gam': 'gm',
    'mauritania': 'mr',
    'mtn': 'mr',
    'níger': 'ne',
    'niger': 'ne',
    'nig': 'ne',
    'chad': 'td',
    'cha': 'td',
    'sudán': 'sd',
    'sudan': 'sd',
    'sud': 'sd',
    'sudán del sur': 'ss',
    'sudan del sur': 'ss',
    'south sudan': 'ss',
    'ssd': 'ss',
    'eritrea': 'er',
    'eri': 'er',
    'somalia': 'so',
    'som': 'so',
    'yibuti': 'dj',
    'djibouti': 'dj',
    'dji': 'dj',
    'libia': 'ly',
    'libya': 'ly',
    'lba': 'ly',
    'namibia': 'na',
    'nam': 'na',
    'botswana': 'bw',
    'bot': 'bw',
    'lesoto': 'ls',
    'lesotho': 'ls',
    'les': 'ls',
    'suazilandia': 'sz',
    'eswatini': 'sz',
    'swaziland': 'sz',
    'swz': 'sz',
    'comoras': 'km',
    'comoros': 'km',
    'com': 'km',
    'madagascar': 'mg',
    'mad': 'mg',
    'mdg': 'mg',
    'mauricio': 'mu',
    'mauritius': 'mu',
    'mri': 'mu',
    'seychelles': 'sc',
    'sey': 'sc',
    'burundi': 'bi',
    'bdi': 'bi',
    'malawi': 'mw',
    'mwi': 'mw',
    'santo tomé y príncipe': 'st',
    'santo tome y principe': 'st',
    'sao tome and principe': 'st',
    'stp': 'st',
  
    // OCEANÍA
    'australia': 'au',
    'aus': 'au',
    'nueva zelanda': 'nz',
    'new zealand': 'nz',
    'nzl': 'nz',
    'papúa nueva guinea': 'pg',
    'papua nueva guinea': 'pg',
    'papua new guinea': 'pg',
    'png': 'pg',
    'fiyi': 'fj',
    'fiji': 'fj',
    'fij': 'fj',
    'samoa': 'ws',
    'sam': 'ws',
    'tonga': 'to',
    'tga': 'to',
    'islas salomón': 'sb',
    'islas salomon': 'sb',
    'solomon islands': 'sb',
    'sol': 'sb',
    'vanuatu': 'vu',
    'van': 'vu',
    'micronesia': 'fm',
    'fsm': 'fm',
    'kiribati': 'ki',
    'kir': 'ki',
    'tuvalu': 'tv',
    'tuv': 'tv',
    'palau': 'pw',
    'plw': 'pw',
    'islas marshall': 'mh',
    'marshall islands': 'mh',
    'msh': 'mh',
    'nauru': 'nr',
    'nru': 'nr',
    'islas cook': 'ck',
    'cook islands': 'ck',
    'cok': 'ck',
    'niue': 'nu',
    'niu': 'nu'
  };